apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskapp-rc
spec:
  replicas: 6
  selector:
    app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: karmanya1804/todoapp:v2 
        ports:
        - containerPort: 3000
